# Generated by Django 3.1.3 on 2020-11-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_accounts', '0002_auto_20201104_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
