# Generated by Django 3.1.3 on 2020-11-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'پست', 'verbose_name_plural': 'پست ها'},
        ),
    ]
